services:
  postgresdb:
    container_name: 'postgres_con'
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=schooldb'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
       
  pgadmin:
    container_name: 'pgadmin_con'
    image: 'dpage/pgadmin4:latest'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@localhost.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
      - 'PGADMIN_LISTEN_PORT=5050'
    ports:
      - '5050:5050'
    depends_on:
      - postgresdb
      
volumes:
  postgres_data: