spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schooldb
    username: myuser
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: school